// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdAoz3kviHAgdABDeXyVUgOJnF8jMjK9Q',
    appId: '1:964869698359:web:f26cc1e9998ae223a2a0b2',
    messagingSenderId: '964869698359',
    projectId: 'nots-1a0cb',
    authDomain: 'nots-1a0cb.firebaseapp.com',
    storageBucket: 'nots-1a0cb.appspot.com',
    measurementId: 'G-KMKT2BM79D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtmpqkfBoX7bm1HfSoUPcn51esydq9Egc',
    appId: '1:964869698359:android:64f3e18e5bac20a7a2a0b2',
    messagingSenderId: '964869698359',
    projectId: 'nots-1a0cb',
    storageBucket: 'nots-1a0cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA57Ja0nU0y1Uvnz-1ruVm0l7DW4y9Rjsg',
    appId: '1:964869698359:ios:c6d4f9bc6100040ba2a0b2',
    messagingSenderId: '964869698359',
    projectId: 'nots-1a0cb',
    storageBucket: 'nots-1a0cb.appspot.com',
    iosBundleId: 'com.example.noteNet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA57Ja0nU0y1Uvnz-1ruVm0l7DW4y9Rjsg',
    appId: '1:964869698359:ios:68a4d6e6e024aa93a2a0b2',
    messagingSenderId: '964869698359',
    projectId: 'nots-1a0cb',
    storageBucket: 'nots-1a0cb.appspot.com',
    iosBundleId: 'com.example.noteNet.RunnerTests',
  );
}
